import { readTextFile, writeTextFile, exists } from '@tauri-apps/plugin-fs';
import { open } from '@tauri-apps/plugin-dialog';
import { join } from '@tauri-apps/api/path';
import type { Project } from '$lib/types';

const MARKER_FILE = '.ganttapp';
const PROJECT_FILE = 'project.json';
const MARKER_VERSION = 1;

/** Normalize dependency type strings that LLMs or humans may write longhand. */
const DEP_TYPE_ALIASES: Record<string, string> = {
  'finish-to-start': 'FS', 'finish to start': 'FS',
  'start-to-start': 'SS',  'start to start': 'SS',
  'finish-to-finish': 'FF','finish to finish': 'FF',
  'start-to-finish': 'SF', 'start to finish': 'SF',
  'fs': 'FS', 'ss': 'SS', 'ff': 'FF', 'sf': 'SF',
};

function normalizeDependencyType(type: string): 'FS' | 'SS' | 'FF' | 'SF' {
  const alias = DEP_TYPE_ALIASES[type.toLowerCase()];
  if (alias) return alias as 'FS' | 'SS' | 'FF' | 'SF';
  if (['FS', 'SS', 'FF', 'SF'].includes(type)) return type as 'FS' | 'SS' | 'FF' | 'SF';
  return 'FS';
}

/** Apply defaults for fields added in newer schema versions (forward-compat migration). */
function migrateProject(project: Project): Project {
  if (!project.kanbanColumns) {
    project.kanbanColumns = [{ id: 'backlog', name: 'Backlog' }];
  }
  function migrateNode(node: Project['children'][number]): void {
    if (!node.todos) node.todos = [];
    if (!node.kanbanColumnId) node.kanbanColumnId = 'backlog';
    for (const dep of node.dependencies ?? []) {
      dep.type = normalizeDependencyType(dep.type);
      if (dep.lag === undefined) dep.lag = 0;
    }
    for (const child of node.children ?? []) {
      migrateNode(child);
    }
  }
  for (const node of project.children ?? []) {
    migrateNode(node);
  }
  return project;
}

/** Check if a directory contains a .ganttapp marker. */
export async function isGanttProject(dirPath: string): Promise<boolean> {
  const markerPath = await join(dirPath, MARKER_FILE);
  return exists(markerPath);
}

/** Read and parse project.json from a directory. */
export async function readProject(dirPath: string): Promise<Project> {
  const filePath = await join(dirPath, PROJECT_FILE);
  const text = await readTextFile(filePath);
  return migrateProject(JSON.parse(text) as Project);
}

/** Write project data as pretty-printed JSON. */
export async function writeProject(dirPath: string, project: Project): Promise<void> {
  const filePath = await join(dirPath, PROJECT_FILE);
  await writeTextFile(filePath, JSON.stringify(project, null, 2));
}

const LLM_EXPORT_FILE = 'project_llm.json';
const LLM_EXPORT_COMMENT =
  'AUTO-GENERATED BY GANTT-APP — DO NOT TOUCH. Rewritten on every save from project.json.';

export async function writeLlmExport(dirPath: string, data: object): Promise<void> {
  const filePath = await join(dirPath, LLM_EXPORT_FILE);
  const payload = { _comment: LLM_EXPORT_COMMENT, ...data };
  await writeTextFile(filePath, JSON.stringify(payload, null, 2));
}

/** Write the .ganttapp marker file. */
export async function writeMarker(dirPath: string): Promise<void> {
  const markerPath = await join(dirPath, MARKER_FILE);
  await writeTextFile(markerPath, JSON.stringify({
    version: MARKER_VERSION,
    createdAt: new Date().toISOString().slice(0, 10),
  }, null, 2));
}

/** Open directory picker. Returns null if user cancels. */
export async function pickProjectFolder(): Promise<string | null> {
  const selected = await open({ directory: true, multiple: false });
  return selected;
}

/** Get the full path to project.json for a given directory (for file watching). */
export async function getProjectFilePath(dirPath: string): Promise<string> {
  return join(dirPath, PROJECT_FILE);
}
